Trials

In [1]:
a = 3
b = -1
print(a+b)

2


In [17]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, -5, 6],
                [7, 8, 9]])

diagonal = np.diagonal(arr)
print(diagonal)

[ 1 -5  9]


In [5]:
diagonal = np.diagonal(arr,offset=1)
print(diagonal)

[2 6]


In [7]:
anti_diagonal = np.diag(np.fliplr(arr))
print("Anti-Diagonal:", anti_diagonal)

Anti-Diagonal: [3 5 7]


In [18]:

total_sum = int(sum(diagonal))
print("Sum of all elements:", total_sum)

Sum of all elements: 5


In [16]:
type(total_sum)

int

In [25]:
def func(arr):
    d1 = np.diagonal(arr)
    print(d1)
    d2 = np.diag(np.fliplr(arr))
    print(d2)
    d1_sum = int(sum(d1))
    print(d1_sum)
    d2_sum = int(sum(d2))
    print(d2_sum)
    ans = abs(d1_sum-d2_sum)
    return ans

In [26]:
func([[1, 2, 3],[4, -5, 6],[7, 8, 9]])

[ 1 -5  9]
[ 3 -5  7]
5
5


0

In [27]:
arr = [[1, 2, 3],[4, -5, 6],[7, 8, 9]]

In [28]:
a1 = [arr[i][i] for i in range(len(arr))]

In [29]:
a1

[1, -5, 9]

In [32]:
a2 = [arr[i][len(arr)-1-i] for i in range(len(arr))]

In [33]:
a2

[3, -5, 7]

In [34]:
def diagonalDifference(arr):
    a1 = [arr[i][i] for i in range(len(arr))]
    a2 = [arr[i][len(arr)-1-i] for i in range(len(arr))]
    a1_sum = sum(a1)
    a2_sum = sum(a2)
    dif = abs(a1_sum - a2_sum)
    return dif

In [37]:
arr = [[1, 2, 3],[4, -5, 6],[7, 8, 8]]

In [38]:
diagonalDifference(arr)

1

In [ ]:
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())

    arr = []

    for _ in range(n):
        arr.append(list(map(int, input().rstrip().split())))

    result = diagonalDifference(arr)

    fptr.write(str(result) + '\n')

    fptr.close()

ACTUAL CODE 

In [ ]:
def diagonalDifference(arr):
    a1 = [arr[i][i] for i in range(len(arr))]
    a2 = [arr[i][len(arr)-1-i] for i in range(len(arr))]
    a1_sum = sum(a1)
    a2_sum = sum(a2)
    dif = abs(a1_sum - a2_sum)
    return dif

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())

    arr = []

    for _ in range(n):
        arr.append(list(map(int, input().rstrip().split())))

    result = diagonalDifference(arr)

    fptr.write(str(result) + '\n')

    fptr.close()